### ISSUE TITLE
Redesign parsing/printing functions for various flavors

### ISSUE THREAD

**Issue by dsheets** [mirage/ocaml-ipaddr#37]
3.0 should adopt a consistent naming scheme for parsing and printing functions with 4 axes of behavior (type, byte-rep/ASCII-rep, exceptions, offsets). Some exceptions for some functions (like `Parse_error` from `of_cstruct_exn` should probably be removed. See #33, #35, #36.

**Comment by dsheets** [comment]
Due to the number of reverse dependencies on this library, I propose making this change in two stages:

1. Add the new interfaces as submodules of the primary compilation units for 2.7.
2. Release 3.0 with the old interfaces removed.

This way, users can start writing against the 3.0 interface but still coexist with users of 2.x. Maintaining multiple major branches is painful but less painful than a flag day. Advice on how to ensure interface continuity welcome. My present thought is to make some kind of conditional preprocessor a requirement for building 3.0 and simply hide the 2.x interface. Perhaps `sed` and some magic (non-doc) comments?

I'll keep this issue up-to-date regarding progress on the new API design so that all stakeholders can help guide the new interface to a happy place.

**Comment by hannesm** [comment]
this has been done in the meantime -- the <bytes> has been renamed to <octet>, there's now -cstruct libraries available, and the to/of_address_string is removed in #99. if there's a more concrete proposal, please feel free to reopen or submit a new issue.
