### ISSUE TITLE
License file is missing

### ISSUE THREAD

**Issue by ericbmerritt** [mirage/ocaml-ipaddr#50]
While the source indicates that this is MIT licensed, without the license file its hard to tell at a glance. For companies with a legal department it could also be an issue of which files are open and which are not. If you add a license file that just removes all the confusion.

**Comment by amirmc** [comment]
*[copying over a comment I made on https://github.com/mirage/ocaml-conduit/issues/71]*

I feel I should add my 2cents (as a general comment for MirageOS libs).

There are three points here.

- Difficult to tell at a glance what the license is.
- Legal departments might not be able to tell which files are open and which are not.
- Adding a license file removes confusion.

I completely agree with the first point (and I think it's important).
I disagree with the second two.

The source itself should be enough information for any legal dept to be able to tell whether a file is open or not.  Adding a separate file doesn't change the due diligence that a legal professional would have to undertake.

In addition, the separate file doesn't necessarily remove confusion as now this repo has license info in a file *and* in the source files.  Although these are consistent, there may be occasions for other libs where code is copied in under a different but compatible licence (admittedly, I think this would be rare -- and likely discouraged -- but the possibility exists).  In that case, the LICENSE file would be misleading.

While I disagree with the second two points, I do agree that making the license info easier for developers to find out is a desirable goal. My approach to this would have been to mention the license info as one line in the README file and point people to the source -- e.g. "LICENSE: Source is released under the ISC license, but please see individual files for details." (or something in that vein).
