### ISSUE TITLE
missing dependency

### ISSUE THREAD

**Issue by hannesm** [mirage/ocaml-ipaddr#66]
2.8.0 dropped a dependency on sexplib, but as far as I can see there is still (automatically generated) code referencing `Sexplib.Sexp.t` et al.: the `jbuild` file contains such a dependency, but the `opam` file does not.

**Comment by bmillwood** [comment]
I ran into this recently as well:

```
# File "lib/conduit.mli", line 1:
# Error: The files /home/ben/.opam/4.05.0/lib/ipaddr/ipaddr.cmi
#        and /home/ben/.opam/4.05.0/lib/sexplib/sexplib__Sexp.cmi
#        make inconsistent assumptions over interface Base__Exn
```

Reinstalling ipaddr fixed it, so I think it was a case of upgrading sexplib and opam not realizing that ipaddr needed to be recompiled.

**Comment by bmillwood** [comment]
See #67
