### ISSUE TITLE
Is Dune broken or am I stupid?

### ISSUE THREAD

**Issue by cfcs** [mirage/ocaml-ipaddr#73]
```
:~/ocaml/ipaddr$ topkg build
      ocamlc lib/.ipaddr.objs/macaddr.{cmi,cmti} (exit 2)
(cd _build/default && /home/user/.opam/4.04.2+fPIC/bin/ocamlc.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -g -bin-annot -I lib/.ipaddr.objs -I /home/user/.opam/4.04.2+fPIC/lib/sexplib -I /home/user/.opam/4.04.2+fPIC/lib/sexplib/0 -no-alias-deps -o lib/.ipaddr.objs/macaddr.cmi -c -intf lib/macaddr.pp.mli)
File "lib/macaddr.mli", line 27, characters 0-27:
Warning 32: unused value compare.
File "lib/macaddr.mli", line 1:
Error: Some fatal warnings were triggered (1 occurrences)
pkg.ml: [ERROR] cmd ['jbuilder' 'build' '--root' '.' '--dev']: exited with 1
```

what am I doing wrong?

**Comment by samoht** [comment]
Not sure what's the question is, but if you want to disallow "warn-as-error" you should remove the `--dev` command which is passed to `jbuilder`.

**Comment by cfcs** [comment]
@samoht Thanks! I think it goes in the category `I'm stupid` :)
I fixed the two things I knew how to fix: https://github.com/mirage/ocaml-ipaddr/pull/74

The remaining error I'm not sure about...
```
:~/ocaml/ipaddr$ jbuilder build
    ocamlopt lib/.ipaddr_top.objs/ipaddr_top.{cmx,o}
File "_none_", line 1:
Warning 58: no cmx file was found in path for module Toploop, and its interface was not compiled with -opaque
```
in my opam dir I have `lib/ocaml/compiler-libs/` has `toploop.cmi` `toploop.cmti` `toploop.cmt`
These are interface files, so I'm assuming that the toplevel provides an implementation at runtime. Not sure how to to make `dune` aware of this?

**Comment by avsm** [comment]
I don't think there's anything we can do to fix this in this repository.  The toploop issue is an upstream one, so it could be reported on Mantis.
