### ISSUE TITLE
This requires Dune >= 1.6

### ISSUE THREAD

**Issue by lindig** [mirage/ocaml-ipaddr#78]
This uses the latest version of Dune (1.6) but doesn't announce it in the opam file - leading to build failures. it would be good to either not demand it in `dune-project` or to announce it in the opam file.

**Comment by hannesm** [comment]
I PRed such a change to opam-repository at https://github.com/ocaml/opam-repository/pull/13193 -- it is not clear to me what the way forward for the repository should be -- does ipaddr really depend on dune 1.6 features? or should the version number in dune-project be lowered?

**Comment by emillon** [comment]
Dune aims to be fully backwards compatible, so there should not be any drawback to adding lower bounds.
