### ISSUE TITLE
can't install cohttp-lwt-unix@2.1.3 because of bug in ipaddr@3.1.0

### ISSUE THREAD

**Issue by Et7f3** [mirage/ocaml-ipaddr#92]
OS: windows 10
package manager: [esy](https://esy.sh)

log file: https://gist.github.com/Et7f3/ae5b0be2ed0331947eb11c55d06313ed#file-failed_log-txt
minimal repro: https://gist.github.com/Et7f3/ae5b0be2ed0331947eb11c55d06313ed#file-package-json

step to repdroduce:
- install esy
- download package.json in empty folder
- open cmd.exe
- travel to the folder that contain only package.json
- type `esy`

some note:
you can see the graph of dependencies in esy.lock/index.json
the first time it will build ocaml compiler so it is availabel inside esy: but once it is build: it will be faster
some warning are already fixed in a PR that is not merged (but esy don't care about warning) so it is the only important section I think
```
    File "lib/ipaddr.ml", line 233, characters 4-24:
    233 |     Macaddr.of_bytes_exn (Bytes.to_string macb)
              ^^^^^^^^^^^^^^^^^^^^
    Error: Unbound value Macaddr.of_bytes_exn
    Hint: Did you mean of_octets_exn?
```

Hello,
I try for a project ot install cohttp-lwt-unix but I get the error above. I have added some information that might be helpful. If you want more info/test I am here.

**Comment by hannesm** [comment]
to me this looks like your version of `macaddr` and `ipaddr` are not compatible. from your log I cannot find which version of `macaddr` is installed. does this problem still exist for you (ipaddr 4.0.0 got released some time ago, thus the problem may have disappeared)?

**Comment by hannesm** [comment]
closing, please reopen if you still encounter this issue with more recent ipaddr releases.
