### ISSUE TITLE
Testing membership in V4 default route

### ISSUE THREAD

**Issue by verbosemode** [mirage/ocaml-ipaddr#97]
It seems like Ipaddr.V4.Prefix.[mem](https://github.com/mirage/ocaml-ipaddr/blob/master/lib/ipaddr.ml#L360) yields an incorrect result, when testing the membership of an IPv4 address in the default route 0.0.0.0/0.

    # Ipaddr.V4.Prefix.mem (Ipaddr.V4.of_string_exn "192.168.0.1")
        (Ipaddr.V4.Prefix.of_string_exn "0.0.0.0/0")
    - : bool = false

The issue seems to be that the conversion of some IP addresses result in a negative number due to the 32 bit signed integers. 192.168.0.1 is converted into -1062731775l.

In the mem function, both values are shifted by 32 bits in that case and are then compared.

    # Int32.shift_right_logical (-1062731775l) 32
    - : int32 = -1062731775l

    # Int32.shift_right_logical 0l 32
    - : int32 = 0l

All other functions of the module, except for V4.Prefix.[subset](https://github.com/mirage/ocaml-ipaddr/blob/master/lib/ipaddr.ml#L362-L363) (which calls mem), seem to behave correctly.

I've just created this issue to track the problem. I'm still trying to come up with a better idea than just returning true for a prefix length of 0.

**Comment by hannesm** [comment]
thanks for looking into this @verbosemode -- looks like the V6 code is fine and doesn't need changes.
It would be great to have (a) failing tests for `Ipv4.Prefix.mem` (b) a fix for the issue (by handling 32 in a special way). If you need a hand (or further discussion / pointers), please let me know. We can as well look further into fixing this via IRC/XMPP.

**Comment by verbosemode** [comment]
The undefined behavior of shift_right_logical seems to manifest only in the toplevel or when explicitly compiling to bytecode.

I've created PR #98 to fix the issue and added some tests for V4.Prefix.mem. The existing tests used Prefix.mem, which in turn calls V6.Prefix.mem and might not hit code in V4.Prefix.mem.
